`timescale 1ns/1ps

module tb_display_controller;

    // Inputs
    reg pixel_clk;
    reg reset;
    reg [11:0] pixel_data_from_mem;

    // Outputs
    wire hsync;
    wire vsync;
    wire display_on;
    wire [19:0] pixel_addr;
    wire [3:0] vga_r;
    wire [3:0] vga_g;
    wire [3:0] vga_b;

    // Instantiate the Unit Under Test (UUT)
    display_controller uut (
        .pixel_clk(pixel_clk),
        .reset(reset),
        .hsync(hsync),
        .vsync(vsync),
        .display_on(display_on),
        .pixel_addr(pixel_addr),
        .pixel_data(pixel_data_from_mem),
        .vga_r(vga_r),
        .vga_g(vga_g),
        .vga_b(vga_b)
    );

    // Clock period for 25.175 MHz clock is ~40ns
    localparam CLK_PERIOD = 40;

    // Image memory
    parameter IMG_WIDTH = 640;
    parameter IMG_HEIGHT = 480;
    parameter IMG_SIZE = IMG_WIDTH * IMG_HEIGHT;
    reg [11:0] image_memory [0:IMG_SIZE-1];

    // File handle for writing VGA signals
    integer vga_out_file;

    initial begin
        // Initialize Inputs
        pixel_clk = 0;
        reset = 1;

        // Load image data from the file generated by MATLAB
        $readmemh("image_data.hex", image_memory);

        // Open file to write simulation output
        vga_out_file = $fopen("vga_signals.txt", "w");
        if (vga_out_file == 0) begin
            $display("Error: Could not open vga_signals.txt");
            $finish;
        end

        // Wait for global reset
        #100;
        reset = 0;
    end

    // Clock generation
    always #(CLK_PERIOD/2) pixel_clk = ~pixel_clk;

    // Read from memory based on the controller's address
    always @(posedge pixel_clk) begin
        if(display_on) begin
            pixel_data_from_mem <= image_memory[pixel_addr];
        end else begin
            // Drive to a known value (black) during blanking intervals
            // This prevents 'x' (unknown) values from propagating.
            pixel_data_from_mem <= 12'h000;
        end
    end

    // Write signals to file for the Python emulator
    // We write on the negative edge to ensure all signals are stable
    always @(negedge pixel_clk) begin
        if (!reset) begin
             $fwrite(vga_out_file, "%b %b %b %d %d %d\n",
                hsync,
                vsync,
                display_on,
                vga_r,
                vga_g,
                vga_b
            );
        end
    end

    // Simulation stop condition (e.g., after one full frame)
    initial begin
        // A full frame is 800 * 525 = 420,000 clock cycles
        // 420000 * 40 ns = 16,800,000 ns = 16.8 ms
        #(17_000_000);
        $display("Simulation of one frame finished.");
        $fclose(vga_out_file);
        $finish;
    end

endmodule

